# 1. Calculate the Area of a Rectangle:

In [4]:
l = float(input("Enter the lenght of rectangle : "))
b = float(input("Enter the bredth of rectangle : "))

A = l*b

print(f"Area of rectangle is {A}")

Enter the lenght of rectangle :  12.5
Enter the bredth of rectangle :  10.9


Area of rectangle is 136.25


# 2. Calculate the Perimeter of a Rectangle:

In [5]:
print(f"The perometer of rectangle is {2*(l+b)}")

The perometer of rectangle is 46.8


# 3. Calculate the Area of a Circle:

In [7]:
from math import pi

In [8]:
pi

3.141592653589793

In [10]:
r = float(input("Enter the radius of circle : "))

A = pi*r**2

print(f"Area of circle is {A:.3f}")

Enter the radius of circle :  5.2


Area of circle is 84.949


# 4. Calculate the Circumference of a Circle:

In [12]:
C = 2*pi*r

print(f"Circumference of circle is {C:.2f}")

Circumference of circle is 32.67


# 5. Calculate the Area of a Triangle:

In [13]:
b = float(input("Enter the base of triangle : "))
h = float(input("Enter the height of triangle : "))

A = 0.5*b*h

print(f"Area of triangle is {A}")

Enter the base of triangle :  10
Enter the height of triangle :  6


Area of triangle is 30.0


In [18]:
a = float(input("Enter the value of a : "))
b = float(input("Enter the value of b : "))
c = float(input("Enter the value of c : "))

s = (a+b+c)/2

print(s)

res = (s*(s-a)*(s-b)*(s-c))
if res<0:
    res = res*-1

A = res**0.5

print(f"Area of trinagle is : {A}")

Enter the value of a :  10
Enter the value of b :  23.5
Enter the value of c :  19.7


26.6
Area of trinagle is : 97.18522727246157


# 6. Calculate the Volume of a Cylinder:
 
A = $\pi * r^2 *h$

In [25]:
r = float(input("Enter the radius of cylinder : "))
h = float(input("enter the height of cylinder : "))

from math import pi
V = pi * r**2 * h

print(F"The volume of cylinder is {V:.2f}")

Enter the radius of cylinder :  20
enter the height of cylinder :  30


The volume of cylinder is 37699.11


# 7. Calculate the Surface Area of a Cylinder:

SA = $2*\pi*r*(r+h)$

In [23]:
SA = 2 * pi * r * (r+h)

In [24]:
SA

848.2300164692441

In [26]:
10+20+30/5

36.0

In [28]:
(10+20+30)/5

12.0

In [29]:
import numpy as np

In [32]:
A = np.array([[1,2],[3,4]])

In [33]:
A

array([[1, 2],
       [3, 4]])

In [35]:
B = np.array([[1,2],[4,5]])

In [36]:
B

array([[1, 2],
       [4, 5]])

In [37]:
A@B

array([[ 9, 12],
       [19, 26]])